//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 12/21/2009 10:16:59 PM
namespace HoNModel
{
    
    /// <summary>
    /// There are no comments for HoNEntities in the schema.
    /// </summary>
    public partial class HoNEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new HoNEntities object using the connection string found in the 'HoNEntities' section of the application configuration file.
        /// </summary>
        public HoNEntities() : 
                base("name=HoNEntities", "HoNEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HoNEntities object.
        /// </summary>
        public HoNEntities(string connectionString) : 
                base(connectionString, "HoNEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new HoNEntities object.
        /// </summary>
        public HoNEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "HoNEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Events in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Events> Events
        {
            get
            {
                if ((this._Events == null))
                {
                    this._Events = base.CreateQuery<Events>("[Events]");
                }
                return this._Events;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Events> _Events;
        /// <summary>
        /// There are no comments for Games in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Games> Games
        {
            get
            {
                if ((this._Games == null))
                {
                    this._Games = base.CreateQuery<Games>("[Games]");
                }
                return this._Games;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Games> _Games;
        /// <summary>
        /// There are no comments for Heroes in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Heroes> Heroes
        {
            get
            {
                if ((this._Heroes == null))
                {
                    this._Heroes = base.CreateQuery<Heroes>("[Heroes]");
                }
                return this._Heroes;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Heroes> _Heroes;
        /// <summary>
        /// There are no comments for Player in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Player> Player
        {
            get
            {
                if ((this._Player == null))
                {
                    this._Player = base.CreateQuery<Player>("[Player]");
                }
                return this._Player;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Player> _Player;
        /// <summary>
        /// There are no comments for Events in the schema.
        /// </summary>
        public void AddToEvents(Events events)
        {
            base.AddObject("Events", events);
        }
        /// <summary>
        /// There are no comments for Games in the schema.
        /// </summary>
        public void AddToGames(Games games)
        {
            base.AddObject("Games", games);
        }
        /// <summary>
        /// There are no comments for Heroes in the schema.
        /// </summary>
        public void AddToHeroes(Heroes heroes)
        {
            base.AddObject("Heroes", heroes);
        }
        /// <summary>
        /// There are no comments for Player in the schema.
        /// </summary>
        public void AddToPlayer(Player player)
        {
            base.AddObject("Player", player);
        }
    }
    /// <summary>
    /// There are no comments for HoNModel.Events in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EventId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HoNModel", Name="Events")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Events : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Events object.
        /// </summary>
        /// <param name="eventId">Initial value of EventId.</param>
        /// <param name="gameId">Initial value of GameId.</param>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="time">Initial value of Time.</param>
        public static Events CreateEvents(int eventId, int gameId, string type, int time)
        {
            Events events = new Events();
            events.EventId = eventId;
            events.GameId = gameId;
            events.Type = type;
            events.Time = time;
            return events;
        }
        /// <summary>
        /// There are no comments for Property EventId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId
        {
            get
            {
                return this._EventId;
            }
            set
            {
                this.OnEventIdChanging(value);
                this.ReportPropertyChanging("EventId");
                this._EventId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("EventId");
                this.OnEventIdChanged();
            }
        }
        private int _EventId;
        partial void OnEventIdChanging(int value);
        partial void OnEventIdChanged();
        /// <summary>
        /// There are no comments for Property GameId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int GameId
        {
            get
            {
                return this._GameId;
            }
            set
            {
                this.OnGameIdChanging(value);
                this.ReportPropertyChanging("GameId");
                this._GameId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GameId");
                this.OnGameIdChanged();
            }
        }
        private int _GameId;
        partial void OnGameIdChanging(int value);
        partial void OnGameIdChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this.ReportPropertyChanging("Type");
                this._Type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Type");
                this.OnTypeChanged();
            }
        }
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this.ReportPropertyChanging("Time");
                this._Time = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Time");
                this.OnTimeChanged();
            }
        }
        private int _Time;
        partial void OnTimeChanging(int value);
        partial void OnTimeChanged();
    }
    /// <summary>
    /// There are no comments for HoNModel.Games in the schema.
    /// </summary>
    /// <KeyProperties>
    /// GameId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HoNModel", Name="Games")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Games : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Games object.
        /// </summary>
        /// <param name="gameId">Initial value of GameId.</param>
        public static Games CreateGames(int gameId)
        {
            Games games = new Games();
            games.GameId = gameId;
            return games;
        }
        /// <summary>
        /// There are no comments for Property GameId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int GameId
        {
            get
            {
                return this._GameId;
            }
            set
            {
                this.OnGameIdChanging(value);
                this.ReportPropertyChanging("GameId");
                this._GameId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GameId");
                this.OnGameIdChanged();
            }
        }
        private int _GameId;
        partial void OnGameIdChanging(int value);
        partial void OnGameIdChanged();
        /// <summary>
        /// There are no comments for Property CollectedDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> CollectedDate
        {
            get
            {
                return this._CollectedDate;
            }
            set
            {
                this.OnCollectedDateChanging(value);
                this.ReportPropertyChanging("CollectedDate");
                this._CollectedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CollectedDate");
                this.OnCollectedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _CollectedDate;
        partial void OnCollectedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCollectedDateChanged();
    }
    /// <summary>
    /// There are no comments for HoNModel.Heroes in the schema.
    /// </summary>
    /// <KeyProperties>
    /// HeroName
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HoNModel", Name="Heroes")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Heroes : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Heroes object.
        /// </summary>
        /// <param name="heroName">Initial value of HeroName.</param>
        public static Heroes CreateHeroes(string heroName)
        {
            Heroes heroes = new Heroes();
            heroes.HeroName = heroName;
            return heroes;
        }
        /// <summary>
        /// There are no comments for Property HeroName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string HeroName
        {
            get
            {
                return this._HeroName;
            }
            set
            {
                this.OnHeroNameChanging(value);
                this.ReportPropertyChanging("HeroName");
                this._HeroName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("HeroName");
                this.OnHeroNameChanged();
            }
        }
        private string _HeroName;
        partial void OnHeroNameChanging(string value);
        partial void OnHeroNameChanged();
    }
    /// <summary>
    /// There are no comments for HoNModel.Player in the schema.
    /// </summary>
    /// <KeyProperties>
    /// PlayerName
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="HoNModel", Name="Player")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Player : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="playerName">Initial value of PlayerName.</param>
        public static Player CreatePlayer(string playerName)
        {
            Player player = new Player();
            player.PlayerName = playerName;
            return player;
        }
        /// <summary>
        /// There are no comments for Property PlayerName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName
        {
            get
            {
                return this._PlayerName;
            }
            set
            {
                this.OnPlayerNameChanging(value);
                this.ReportPropertyChanging("PlayerName");
                this._PlayerName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PlayerName");
                this.OnPlayerNameChanged();
            }
        }
        private string _PlayerName;
        partial void OnPlayerNameChanging(string value);
        partial void OnPlayerNameChanged();
    }
}
