//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "", ConfigurationName = "ISC2ReplayHost")]
public interface ISC2ReplayHost
{

	[System.ServiceModel.OperationContractAttribute(Action = "urn:ISC2ReplayHost/GetReplayNames", ReplyAction = "urn:ISC2ReplayHost/GetReplayNamesResponse")]
	string[] GetReplayNames();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISC2ReplayHostChannel : ISC2ReplayHost, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SC2ReplayHostClient : System.ServiceModel.ClientBase<ISC2ReplayHost>, ISC2ReplayHost
{

	public SC2ReplayHostClient()
	{
	}

	public SC2ReplayHostClient(string endpointConfigurationName) :
		base(endpointConfigurationName)
	{
	}

	public SC2ReplayHostClient(string endpointConfigurationName, string remoteAddress) :
		base(endpointConfigurationName, remoteAddress)
	{
	}

	public SC2ReplayHostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
		base(endpointConfigurationName, remoteAddress)
	{
	}

	public SC2ReplayHostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
		base(binding, remoteAddress)
	{
	}

	public string[] GetReplayNames()
	{
		return base.Channel.GetReplayNames();
	}
}
